# Generated by Django 2.2.7 on 2019-11-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191117_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='imgUp', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='requerimientos',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
