# Generated by Django 2.2.7 on 2019-11-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191118_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='imgUp/', width_field='width_field'),
        ),
    ]
